name: Discord Alert

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send alert to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"🚀 Novo push no repositório projeto-faculdade por ${{ github.actor }} na branch main. Commit: ${{ github.event.head_commit.message }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
